schemaVersion: 2.2.0
metadata:
  name: che-blog
components:
  - name: jekyll
    container:
      image: quay.io/eclipse/che-blog:next
      memoryLimit: 4Gi
      cpuLimit: '2'
      memoryRequest: 1Gi
      cpuRequest: 500m
      endpoints:
        - exposure: public
          name: live-reload
          protocol: http
          targetPort: 35729
        - exposure: public
          name: jekyll
          protocol: http
          targetPort: 4000
commands:
  - id: bundle-install
    exec:
      label: 0. Install Gemfile dependencies
      component: jekyll
      commandLine: bundle install
      group:
        kind: build
        isDefault: true
  - id: start-jekyll-server
    exec:
      label: 1. Start the jekyll based blog server
      component: jekyll
      # commandLine: bundle jekyll serve --incremental --watch --host 0.0.0.0 --livereload --livereload-port 35729
      commandLine: bundle exec jekyll serve --incremental --watch --host 0.0.0.0
      group:
        kind: run
        isDefault: true
  - id: jekyll-clean
    exec:
      component: jekyll
      commandLine: bundle exec jekyll clean
      group:
        kind: build
        isDefault: false
