# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eclipse Che Blog
email: che-dev@eclipse.org
description: >- # this means to ignore newlines until "baseurl:"
  Eclipse Che runs IDEs in Kubernetes.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://che.eclipseprojects.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: eclipse_che
github_username:  eclipse-che
header_pages:
  - index.markdown

google_analytics: "UA-215676970-1"

# Build settings
theme: minima
plugins:
  - jekyll-asciidoc
  - jekyll-feed

highlighter: rouge

asciidoc:
  attributes:
    # for the project
    broker-ver: "v3.4.0"
    che-devfile-registry-container-image: quay.io/eclipse/che-devfile-registry
    che-devfile-registry-directory: che-devfile-registry
    che-plugin-registry-container-image: quay.io/eclipse/che-plugin-registry
    che-plugin-registry-directory: che-plugin-registry
    devworkspace: DevWorkspace
    identity-provider-docs-url: https://www.keycloak.org/docs/
    identity-provider-id: keycloak
    identity-provider-image-url: quay.io/eclipse/che-keycloak
    identity-provider-url: https://www.keycloak.org/
    identity-provider-version: "15.0"
    identity-provider: Keycloak
    image-puller-cr-name: KubernetesImagePuller
    image-puller-deployment-id: kubernetes-image-puller-operator
    image-puller-deployment-name: kubernetes-image-puller
    image-puller-image-name: quay.io/eclipse/kubernetes-image-puller
    image-puller-image-tag: latest
    image-puller-images: "java11-maven=quay.io/eclipse/che-java11-maven:nightly;che-theia=quay.io/eclipse/che-theia:next;java-plugin-runner=eclipse/che-remote-plugin-runner-java8:latest;"
    image-puller-name-short: Image Puller
    image-puller-name: Kubernetes Image Puller
    image-puller-namespace: k8s-image-puller
    image-puller-operator-id: kubernetes-image-puller-operator
    image-puller-operator-name: Kubernetes Image Puller Operator
    image-puller-operator-repository-name: kubernetes-image-puller-operator
    image-puller-repository-name: kubernetes-image-puller
    kube-ver-min: "1.19"
    kubernetes: Kubernetes
    link-accessing-a-git-repository-via-https: xref:end-user-guide:version-control.adoc#accessing-a-git-repository-via-https_che[Accessing a Git repository using HTTPS]
    link-advanced-configuration-options-for-the-che-server: xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc[]
    link-advanced-configuration-options: xref:installation-guide:advanced-configuration-options-for-the-che-server-component.adoc[]
    link-building-a-custom-plug-in-registry: xref:administration-guide:building-and-running-a-custom-registry-image.adoc#building-a-custom-devfile-registry_che[Building a custom devfile registry]
    link-cli-github: https://github.com/che-incubator/chectl
    link-identity-provider-documentation-openshift-3: https://www.keycloak.org/docs/latest/server_admin/#openshift-3
    link-identity-provider-documentation-openshift-4: https://www.keycloak.org/docs/latest/server_admin/#openshift-4
    link-identity-provider-github: "https://www.keycloak.org/docs/15.0//server_admin/#github"
    link-identity-provider-oidc: "https://www.keycloak.org/docs/15.0/server_admin/#_oidc"
    link-identity-provider-saml: "https://www.keycloak.org/docs/15.0/server_admin/#saml-v2-0-identity-providers"
    link-installing-an-instance: xref:installation-guide:installing-che.adoc[]
    link-server-identity-provider-dockerfile-location: https://github.com/eclipse-che/che-server/tree/main/dockerfiles/keycloak
    link-viewing-the-state-of-the-cluster-deployment-using-openshift-4-cli-tools: xref:overview:installing-che-on-openshift-4-using-operatorhub.adoc[]
    namespace: namespace # In context: API namespace
    nodejs-stack: nodejs
    ocp: OpenShift&#160;Container&#160;Platform
    ocp3-ver: "3.11"
    ocp4-ver: "4.6"
    orch-cli-link: link:https://kubernetes.io/docs/reference/kubectl/overview/[Overview of kubectl]
    orch-cli: kubectl
    orch-ingress: Kubernetes Ingress
    orch-name: Kubernetes
    orch-namespace: namespace # In context: orch-name orch-namespace
    osd: OpenShift&#160;Dedicated
    platforms-cli: "`kubectl` or `oc`"
    platforms-identity-provider: "Identity Provider (Keycloak or RH-SSO)"
    platforms-ingress: Kubernetes Ingress or OpenShift Route
    platforms-name: Kubernetes or OpenShift
    platforms-namespace: Kubernetes namespace or OpenShift project
    postgresql-image-url: quay.io/eclipse/che-postgres
    prod-checluster: eclipse-che
    prod-cli: chectl
    prod-deployment: che
    prod-docs-url: https://www.eclipse.org/che/docs
    prod-home: /home/user
    prod-host: che-host
    prod-id-short: che
    prod-id: eclipse-che
    prod-namespace: eclipse-che
    prod-operator-image-name: che-operator
    prod-operator: che-operator
    prod-prev-ver-major: "6"
    prod-prev-ver: "7.39"
    prod-short: Che
    prod-upstream: Eclipse{nbsp}Che
    prod-url: https://che-host
    prod-ver-major: "7"
    prod-ver-patch: "7.40.1"
    prod-ver: "7.40"
    prod-workspace: che-ws
    prod: Eclipse&#160;Che
    prod2: Eclipse&#160;Che
    project-context: che
    repo-path: ""
    theia-endpoint-image: eclipse/che-theia-endpoint-runtime:next
    url-devfile-registry-repo: https://github.com/eclipse/che-devfile-registry
    url-plug-in-registry-repo: https://github.com/eclipse/che-plugin-registry

asciidoctor:
  attributes:
    idprefix: _
    source-highlighter: rouge
    rouge-css: style
    rouge-style: monokai # <-- https://rouge-ruby.github.io/docs/Rouge/Themes.html
    # rouge-css: class
    # rouge-stylesheet: asciidoc-rouge.css


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
