---
title: Contributing to Eclipse Che documentation
layout: post
author: Jana Vrbkova
description: >-
  Contribute to Eclipse Che documentation using an Eclipse Che workspace.
categories: []
keywords: ['che-docs', 'documentation', 'write', 'contribute']
slug: /@deerskindoll/contributing-to-che-docs
---

= Contributing to Eclipse Che documentation

Writing about Eclipse Che is even easier than you think.
The link:https://github.com/eclipse-che/che-docs[Eclipse Che documentation repository on GitHub] was created with community contribution in mind,
featuring tools you need to create and test your content.
And from the initial draft to submitting a PR,
you can do it all in the environment you're already familiar with: an Eclipse Che workspace.

.Getting started

Use either link:https://eclipse.dev/che/docs/stable/administration-guide/installing-che/[your own Eclipse Che installation]
or click the Developer Workspace button in the che-docs repository README file.
This opens a clone of the repository in an Eclipse Che workspace hosted
by Red Hat in the link:https://developers.redhat.com/developer-sandbox?source=sso[Developer Sandbox].
Alternatively, you can click this button:

[![Contribute](https://www.eclipse.org/che/contribute.svg)](https://workspaces.openshift.com/f?url=https://github.com/eclipse/che-docs)

.How does it work?

What about the che-docs repository makes using an Eclipse Che workspace to contribute content so convenient? The following two elements:
//files? items? tools?

* link:https://eclipse.dev/che/docs/stable/end-user-guide/devfile-introduction/[devfile]
* list of link:https://eclipse.dev/che/docs/stable/end-user-guide/microsoft-visual-studio-code-open-source-ide/#automating-installation-of-microsoft-visual-studio-code-extensions-at-workspace-startup[automatically installed Microsoft Visual Studio Code extensions]

Let's look at the devfile first.
The che-docs repository contains a simple devfile
that defines the basic features of the che-docs workspace.
It also includes a command for building a preview of your newly created content:

[source, code]
----
# sh tools/preview.sh
----

This is helpful not only for checking the layout of the document but also for making sure that embedded images,
links and code blocks are displayed correctly.

//why does the workspace start in VS Code, anyway? it's not explicitly mentioned in the devfile.

By default, the che-docs workspace launches with Visual Studio Code - Open Source ("Code - OSS") as the IDE.





//vale sync command!!!!

[IMPORTANT]
====
The Vale extension included in the che-docs repository follows the grammatical,
spelling and stylistic rules from the link:https://redhat-documentation.github.io/supplementary-style-guide/[Red Hat supplementary style guide].

Before you start writing,
read the section about link:https://redhat-documentation.github.io/supplementary-style-guide/#technical-examples[documenting commands].
====

.Writing tips

A good technical document is easy to read and easy to follow.
Here are a few tips that will help you write great technical content:

* Keep it simple. Avoid self-referential language ("this article is about..."), overly long introductions, and deep-dives into the feature's history.
* Keep it accessible. Short paragraphs, sentences and words make your content easy to read.
* Keep the focus on the user. Write the content around what the user can achieve when they follow your instructions.

if you want to learn more about technical writing in general,
check out the link:https://developers.google.com/style[Google developer documentation style guide].

Happy writing!